export type NodeCategory =
  | "Frontend"
  | "Backend"
  | "Mobile"
  | "IoT"
  | "Networking"
  | "Data"
  | "Core"
  | "Writing";

export type NodeKind =
  | "core"
  | "section"
  | "project"
  | "skill"
  | "service"
  | "metric";

export interface NetworkNode {
  id: string;
  label: string;
  kind: NodeKind;
  category: NodeCategory;
  position: [number, number, number];
  orbit: number;
  summary: string;
  latency: string;
  throughput: string;
  tags?: string[];
}

export interface NetworkEdge {
  id: string;
  from: string;
  to: string;
  kind: "fiber" | "wireless" | "telemetry" | "backbone";
  category: NodeCategory;
  bandwidth: string;
  jitter: string;
}

export interface ProjectCaseStudy {
  tagline: string;
  overview: string;
  highlights: string[];
  architecture: { label: string; detail: string }[];
  database: {
    engine: string;
    schema: string[];
    replication: string;
  };
  apis: { method: string; route: string; description: string; runtime: string }[];
  metrics: { label: string; value: string; description: string }[];
  timeline: string;
  status: "In Production" | "In Exploration" | "Open Source";
  stack: string[];
}

export const filterCategories: NodeCategory[] = [
  "Frontend",
  "Backend",
  "Mobile",
  "IoT",
  "Networking",
];

export const networkNodes: NetworkNode[] = [
  {
    id: "smit-core",
    label: "SMIT DHAMELIYA",
    kind: "core",
    category: "Core",
    position: [0, 0, 0],
    orbit: 0,
    summary: "Full-stack developer weaving responsive software and resilient networks.",
    latency: "0.3ms",
    throughput: "∞",
    tags: ["Full Stack", "Systems", "IoT"],
  },
  {
    id: "section-projects",
    label: "Project Constellation",
    kind: "section",
    category: "Backend",
    position: [6.2, 1.1, -2.6],
    orbit: 1,
    summary: "12 production-grade case studies mapped as luminous routes.",
    latency: "1.2ms",
    throughput: "48Gbps",
    tags: ["Case Studies"],
  },
  {
    id: "section-skills",
    label: "Skill Mesh",
    kind: "section",
    category: "Frontend",
    position: [-6.4, 1.4, 1.6],
    orbit: 2,
    summary: "Stacks, frameworks, and protocols that power the atlas.",
    latency: "0.9ms",
    throughput: "32Gbps",
    tags: ["Capabilities"],
  },
  {
    id: "section-mobile",
    label: "Mobile Orbit",
    kind: "section",
    category: "Mobile",
    position: [2.2, -4.8, 3.4],
    orbit: 3,
    summary: "React Native and Android experiences with native polish.",
    latency: "1.6ms",
    throughput: "18Gbps",
    tags: ["React Native", "Android"],
  },
  {
    id: "section-databases",
    label: "Data Backbone",
    kind: "section",
    category: "Data",
    position: [-2.1, -4.6, -3.3],
    orbit: 4,
    summary: "Relational designs tuned for speed and observability.",
    latency: "1.1ms",
    throughput: "22Gbps",
    tags: ["SQL", "Observability"],
  },
  {
    id: "section-iot",
    label: "IoT Perimeter",
    kind: "section",
    category: "IoT",
    position: [0.4, 5.9, 2.6],
    orbit: 5,
    summary: "Embedded sensors, mesh gateways, and resilient telemetry.",
    latency: "2.2ms",
    throughput: "12Gbps",
    tags: ["Embedded", "Telemetry"],
  },
  {
    id: "section-oss",
    label: "Signals & Writing",
    kind: "section",
    category: "Writing",
    position: [0.6, -0.6, -6.4],
    orbit: 6,
    summary: "Open-source, articles, and talks on distributed UX.",
    latency: "1.8ms",
    throughput: "9Gbps",
    tags: ["Knowledge"],
  },
  {
    id: "packet-oracle",
    label: "Packet Oracle",
    kind: "project",
    category: "Backend",
    position: [9.1, 2.6, -1.2],
    orbit: 10,
    summary: "Real-time observability suite visualizing cloud + edge traffic.",
    latency: "3.6ms",
    throughput: "64Gbps",
    tags: ["Next.js", "Hono", "PostgreSQL"],
  },
  {
    id: "aether-routing",
    label: "Aether Routing",
    kind: "project",
    category: "Networking",
    position: [7.2, -0.8, 4.5],
    orbit: 11,
    summary: "Global load balancer with programmable BGP guardrails.",
    latency: "4.4ms",
    throughput: "72Gbps",
    tags: ["Node", "BGP", "Redis"],
  },
  {
    id: "lattice-commerce",
    label: "Lattice Commerce",
    kind: "project",
    category: "Frontend",
    position: [8.4, 3.8, 3.3],
    orbit: 12,
    summary: "Composable commerce OS with dynamic pricing mesh.",
    latency: "2.8ms",
    throughput: "44Gbps",
    tags: ["React", "Next.js", "MySQL"],
  },
  {
    id: "nebula-journal",
    label: "Nebula Journal",
    kind: "project",
    category: "Frontend",
    position: [6.4, -3.9, -2.7],
    orbit: 13,
    summary: "Next.js knowledge base streaming MDX across teams.",
    latency: "3.2ms",
    throughput: "28Gbps",
    tags: ["Next.js", "MDX", "Edge"],
  },
  {
    id: "relay-mobile",
    label: "Relay Mobile",
    kind: "project",
    category: "Mobile",
    position: [3.1, -7.3, 4.2],
    orbit: 14,
    summary: "React Native field companion with offline-first sync.",
    latency: "5.0ms",
    throughput: "16Gbps",
    tags: ["React Native", "SQLite", "Expo"],
  },
  {
    id: "flux-observatory",
    label: "Flux Observatory",
    kind: "project",
    category: "IoT",
    position: [-1.2, 7.8, 3.6],
    orbit: 15,
    summary: "Edge analytics for environmental telemetry using LoRaWAN.",
    latency: "6.6ms",
    throughput: "8Gbps",
    tags: ["IoT", "LoRa", "Time-series"],
  },
  {
    id: "mesh-sentinel",
    label: "Mesh Sentinel",
    kind: "project",
    category: "Networking",
    position: [-5.9, 6.6, -0.8],
    orbit: 16,
    summary: "Self-healing network monitor with anomaly forensics.",
    latency: "4.9ms",
    throughput: "38Gbps",
    tags: ["Node", "React", "Telemetry"],
  },
  {
    id: "orbit-scheduler",
    label: "Orbit Scheduler",
    kind: "project",
    category: "Backend",
    position: [5.4, 5.9, -4.5],
    orbit: 17,
    summary: "Hono.js workflow engine orchestrating event-driven fleets.",
    latency: "3.8ms",
    throughput: "41Gbps",
    tags: ["Hono", "TypeScript", "Queues"],
  },
  {
    id: "pulse-care",
    label: "Pulse Care",
    kind: "project",
    category: "IoT",
    position: [-3.6, -6.3, 2.4],
    orbit: 18,
    summary: "Remote vitals mesh bridging hospitals and home devices.",
    latency: "5.5ms",
    throughput: "14Gbps",
    tags: ["IoT", "React Native", "MQTT"],
  },
  {
    id: "quantum-fleet",
    label: "Quantum Fleet",
    kind: "project",
    category: "Mobile",
    position: [1.1, -8.6, -3.5],
    orbit: 19,
    summary: "Predictive fleet intelligence with adaptive routing.",
    latency: "4.7ms",
    throughput: "22Gbps",
    tags: ["Node", "Maps", "Edge"],
  },
  {
    id: "terra-lens",
    label: "Terra Lens",
    kind: "project",
    category: "Data",
    position: [-6.8, -5.5, -4.4],
    orbit: 20,
    summary: "Geospatial impact dashboard with sensor overlays.",
    latency: "4.2ms",
    throughput: "24Gbps",
    tags: ["PostgreSQL", "GIS", "Next.js"],
  },
  {
    id: "signal-garden",
    label: "Signal Garden",
    kind: "project",
    category: "Writing",
    position: [2.2, 6.8, 5.1],
    orbit: 21,
    summary: "Thought leadership garden on distributed UX patterns.",
    latency: "3.4ms",
    throughput: "12Gbps",
    tags: ["Writing", "Talks"],
  },
  {
    id: "skill-react",
    label: "React",
    kind: "skill",
    category: "Frontend",
    position: [-7.4, 0.8, 1.2],
    orbit: 101,
    summary: "Hooks-first architecture for resilient UIs.",
    latency: "0.9ms",
    throughput: "28Gbps",
    tags: ["Concurrent", "RSC"],
  },
  {
    id: "skill-next",
    label: "Next.js",
    kind: "skill",
    category: "Frontend",
    position: [-7.9, 2.6, 0.4],
    orbit: 102,
    summary: "App Router expert blending SSR, ISR, and Edge.",
    latency: "0.8ms",
    throughput: "30Gbps",
    tags: ["App Router", "Edge"],
  },
  {
    id: "skill-typescript",
    label: "TypeScript",
    kind: "skill",
    category: "Backend",
    position: [-6.6, -0.4, 2.7],
    orbit: 103,
    summary: "Types as contracts across services and devices.",
    latency: "0.7ms",
    throughput: "34Gbps",
    tags: ["Generics", "DX"],
  },
  {
    id: "skill-node",
    label: "Node.js",
    kind: "skill",
    category: "Backend",
    position: [-5.4, 2.6, 3.8],
    orbit: 104,
    summary: "Event-driven backends tuned for throughput.",
    latency: "0.9ms",
    throughput: "38Gbps",
    tags: ["Streams", "Workers"],
  },
  {
    id: "skill-express",
    label: "Express.js",
    kind: "skill",
    category: "Backend",
    position: [-4.8, 0.6, 4.8],
    orbit: 105,
    summary: "Classic APIs modernized with OpenAPI and metrics.",
    latency: "1.0ms",
    throughput: "26Gbps",
    tags: ["REST", "OpenAPI"],
  },
  {
    id: "skill-hono",
    label: "Hono.js",
    kind: "skill",
    category: "Backend",
    position: [-5.8, 3.8, -0.4],
    orbit: 106,
    summary: "Hyperlight edge routing with type-safe middleware.",
    latency: "0.6ms",
    throughput: "31Gbps",
    tags: ["Edge", "Cloudflare"],
  },
  {
    id: "skill-react-native",
    label: "React Native",
    kind: "skill",
    category: "Mobile",
    position: [-3.1, -5.2, 4.2],
    orbit: 107,
    summary: "Native-quality experiences with Hermes optimizations.",
    latency: "1.3ms",
    throughput: "21Gbps",
    tags: ["Expo", "Animations"],
  },
  {
    id: "skill-android",
    label: "Android",
    kind: "skill",
    category: "Mobile",
    position: [-1.8, -6.0, 3.8],
    orbit: 108,
    summary: "Kotlin-first integrations with Jetpack and native modules.",
    latency: "1.5ms",
    throughput: "19Gbps",
    tags: ["Compose", "BLE"],
  },
  {
    id: "skill-mysql",
    label: "MySQL",
    kind: "skill",
    category: "Data",
    position: [-2.4, -5.9, -4.6],
    orbit: 109,
    summary: "Sharded OLTP with plan inspection and indexes.",
    latency: "1.2ms",
    throughput: "27Gbps",
    tags: ["InnoDB", "Plan Cache"],
  },
  {
    id: "skill-postgres",
    label: "PostgreSQL",
    kind: "skill",
    category: "Data",
    position: [-3.9, -4.8, -4.8],
    orbit: 110,
    summary: "Timescale + PostGIS for advanced analytics.",
    latency: "1.1ms",
    throughput: "29Gbps",
    tags: ["PostGIS", "Timescale"],
  },
  {
    id: "skill-prisma",
    label: "Prisma",
    kind: "skill",
    category: "Backend",
    position: [-1.2, -3.6, -4.9],
    orbit: 111,
    summary: "Data layer with generated zod-powered validators.",
    latency: "0.9ms",
    throughput: "24Gbps",
    tags: ["ORM", "DX"],
  },
  {
    id: "skill-zustand",
    label: "Zustand",
    kind: "skill",
    category: "Frontend",
    position: [-5.6, 0.4, -1.2],
    orbit: 112,
    summary: "Predictable state mesh for high-FPS UI.",
    latency: "0.8ms",
    throughput: "18Gbps",
    tags: ["State", "Slices"],
  },
  {
    id: "skill-three",
    label: "Three.js",
    kind: "skill",
    category: "Frontend",
    position: [-4.4, 1.6, -2.5],
    orbit: 113,
    summary: "GPU storytelling with shader-driven visuals.",
    latency: "1.4ms",
    throughput: "23Gbps",
    tags: ["R3F", "Shaders"],
  },
  {
    id: "skill-iot",
    label: "IoT Systems",
    kind: "skill",
    category: "IoT",
    position: [-0.8, 5.9, 2.2],
    orbit: 114,
    summary: "Sensor mesh design with resilient gateways.",
    latency: "1.9ms",
    throughput: "15Gbps",
    tags: ["ESP32", "LoRa"],
  },
  {
    id: "skill-mqtt",
    label: "MQTT",
    kind: "skill",
    category: "IoT",
    position: [0.9, 6.5, 1.2],
    orbit: 115,
    summary: "QoS-aware messaging for telemetry and control.",
    latency: "2.1ms",
    throughput: "12Gbps",
    tags: ["QoS", "Bridges"],
  },
  {
    id: "skill-networking",
    label: "Networking",
    kind: "skill",
    category: "Networking",
    position: [-5.4, 5.4, 0.8],
    orbit: 116,
    summary: "Routing, BGP, and observability for dependable infra.",
    latency: "1.5ms",
    throughput: "36Gbps",
    tags: ["BGP", "SDN"],
  },
  {
    id: "skill-websockets",
    label: "WebSockets",
    kind: "skill",
    category: "Backend",
    position: [-3.8, 3.6, -3.8],
    orbit: 117,
    summary: "Realtime sync engines with presence & TTL flows.",
    latency: "1.0ms",
    throughput: "21Gbps",
    tags: ["Realtime", "Presence"],
  },
  {
    id: "skill-tailwind",
    label: "Tailwind CSS",
    kind: "skill",
    category: "Frontend",
    position: [-4.8, -1.2, 1.4],
    orbit: 118,
    summary: "Design systems rendered as responsive primitives.",
    latency: "0.7ms",
    throughput: "19Gbps",
    tags: ["Design System"],
  },
  {
    id: "skill-motion",
    label: "Motion",
    kind: "skill",
    category: "Frontend",
    position: [-3.3, -0.2, -2.8],
    orbit: 119,
    summary: "Spring micro-interactions tuned with Motion.",
    latency: "0.6ms",
    throughput: "16Gbps",
    tags: ["Framer", "Transitions"],
  },
  {
    id: "skill-graphql",
    label: "GraphQL",
    kind: "skill",
    category: "Backend",
    position: [-2.6, 2.8, -4.4],
    orbit: 120,
    summary: "Gateway design with persisted queries & caching.",
    latency: "1.2ms",
    throughput: "20Gbps",
    tags: ["Apollo", "Yoga"],
  },
  {
    id: "skill-docker",
    label: "Docker",
    kind: "skill",
    category: "Backend",
    position: [-1.5, 3.8, -2.9],
    orbit: 121,
    summary: "Containerized delivery with health probes.",
    latency: "1.0ms",
    throughput: "22Gbps",
    tags: ["CI/CD", "Compose"],
  },
  {
    id: "skill-open-source",
    label: "Open Source",
    kind: "service",
    category: "Writing",
    position: [1.6, -0.9, -5.8],
    orbit: 201,
    summary: "Maintainer of tools for routing UX and telemetry.",
    latency: "2.0ms",
    throughput: "11Gbps",
    tags: ["Docs", "Community"],
  },
  {
    id: "skill-writing",
    label: "Technical Writing",
    kind: "service",
    category: "Writing",
    position: [0.2, -1.8, -6.8],
    orbit: 202,
    summary: "Explaining distributed systems with clarity.",
    latency: "2.4ms",
    throughput: "8Gbps",
    tags: ["Workshops", "Talks"],
  },
];

export const networkEdges: NetworkEdge[] = [
  {
    id: "edge-core-projects",
    from: "smit-core",
    to: "section-projects",
    kind: "backbone",
    category: "Backend",
    bandwidth: "100Gbps",
    jitter: "0.2ms",
  },
  {
    id: "edge-core-skills",
    from: "smit-core",
    to: "section-skills",
    kind: "backbone",
    category: "Frontend",
    bandwidth: "96Gbps",
    jitter: "0.3ms",
  },
  {
    id: "edge-core-mobile",
    from: "smit-core",
    to: "section-mobile",
    kind: "backbone",
    category: "Mobile",
    bandwidth: "72Gbps",
    jitter: "0.4ms",
  },
  {
    id: "edge-core-databases",
    from: "smit-core",
    to: "section-databases",
    kind: "backbone",
    category: "Data",
    bandwidth: "88Gbps",
    jitter: "0.4ms",
  },
  {
    id: "edge-core-iot",
    from: "smit-core",
    to: "section-iot",
    kind: "backbone",
    category: "IoT",
    bandwidth: "68Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-core-oss",
    from: "smit-core",
    to: "section-oss",
    kind: "backbone",
    category: "Writing",
    bandwidth: "40Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-projects-packet-oracle",
    from: "section-projects",
    to: "packet-oracle",
    kind: "fiber",
    category: "Backend",
    bandwidth: "54Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-projects-aether-routing",
    from: "section-projects",
    to: "aether-routing",
    kind: "fiber",
    category: "Networking",
    bandwidth: "52Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-projects-lattice-commerce",
    from: "section-projects",
    to: "lattice-commerce",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "46Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-projects-nebula-journal",
    from: "section-projects",
    to: "nebula-journal",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "36Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-projects-relay-mobile",
    from: "section-projects",
    to: "relay-mobile",
    kind: "fiber",
    category: "Mobile",
    bandwidth: "32Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-projects-flux-observatory",
    from: "section-projects",
    to: "flux-observatory",
    kind: "fiber",
    category: "IoT",
    bandwidth: "28Gbps",
    jitter: "1.2ms",
  },
  {
    id: "edge-projects-mesh-sentinel",
    from: "section-projects",
    to: "mesh-sentinel",
    kind: "fiber",
    category: "Networking",
    bandwidth: "34Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-projects-orbit-scheduler",
    from: "section-projects",
    to: "orbit-scheduler",
    kind: "fiber",
    category: "Backend",
    bandwidth: "38Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-projects-pulse-care",
    from: "section-projects",
    to: "pulse-care",
    kind: "fiber",
    category: "IoT",
    bandwidth: "26Gbps",
    jitter: "1.1ms",
  },
  {
    id: "edge-projects-quantum-fleet",
    from: "section-projects",
    to: "quantum-fleet",
    kind: "fiber",
    category: "Mobile",
    bandwidth: "31Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-projects-terra-lens",
    from: "section-projects",
    to: "terra-lens",
    kind: "fiber",
    category: "Data",
    bandwidth: "30Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-projects-signal-garden",
    from: "section-oss",
    to: "signal-garden",
    kind: "fiber",
    category: "Writing",
    bandwidth: "18Gbps",
    jitter: "1.3ms",
  },
  {
    id: "edge-skills-react",
    from: "section-skills",
    to: "skill-react",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "28Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-skills-next",
    from: "section-skills",
    to: "skill-next",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "29Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-skills-typescript",
    from: "section-skills",
    to: "skill-typescript",
    kind: "wireless",
    category: "Backend",
    bandwidth: "30Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-skills-node",
    from: "section-skills",
    to: "skill-node",
    kind: "wireless",
    category: "Backend",
    bandwidth: "31Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-skills-express",
    from: "section-skills",
    to: "skill-express",
    kind: "wireless",
    category: "Backend",
    bandwidth: "26Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-skills-hono",
    from: "section-skills",
    to: "skill-hono",
    kind: "wireless",
    category: "Backend",
    bandwidth: "27Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-skills-react-native",
    from: "section-mobile",
    to: "skill-react-native",
    kind: "wireless",
    category: "Mobile",
    bandwidth: "18Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-skills-android",
    from: "section-mobile",
    to: "skill-android",
    kind: "wireless",
    category: "Mobile",
    bandwidth: "17Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-skills-mysql",
    from: "section-databases",
    to: "skill-mysql",
    kind: "wireless",
    category: "Data",
    bandwidth: "22Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-skills-postgres",
    from: "section-databases",
    to: "skill-postgres",
    kind: "wireless",
    category: "Data",
    bandwidth: "25Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-skills-prisma",
    from: "section-databases",
    to: "skill-prisma",
    kind: "wireless",
    category: "Backend",
    bandwidth: "21Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-skills-zustand",
    from: "section-skills",
    to: "skill-zustand",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "19Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-skills-three",
    from: "section-skills",
    to: "skill-three",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "18Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-skills-iot",
    from: "section-iot",
    to: "skill-iot",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "14Gbps",
    jitter: "1.3ms",
  },
  {
    id: "edge-skills-mqtt",
    from: "section-iot",
    to: "skill-mqtt",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "12Gbps",
    jitter: "1.4ms",
  },
  {
    id: "edge-skills-networking",
    from: "section-iot",
    to: "skill-networking",
    kind: "telemetry",
    category: "Networking",
    bandwidth: "20Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-skills-websockets",
    from: "section-skills",
    to: "skill-websockets",
    kind: "wireless",
    category: "Backend",
    bandwidth: "20Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-skills-tailwind",
    from: "section-skills",
    to: "skill-tailwind",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "17Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-skills-motion",
    from: "section-skills",
    to: "skill-motion",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "18Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-skills-graphql",
    from: "section-skills",
    to: "skill-graphql",
    kind: "wireless",
    category: "Backend",
    bandwidth: "19Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-skills-docker",
    from: "section-skills",
    to: "skill-docker",
    kind: "wireless",
    category: "Backend",
    bandwidth: "22Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-skills-open-source",
    from: "section-oss",
    to: "skill-open-source",
    kind: "fiber",
    category: "Writing",
    bandwidth: "14Gbps",
    jitter: "1.1ms",
  },
  {
    id: "edge-skills-writing",
    from: "section-oss",
    to: "skill-writing",
    kind: "fiber",
    category: "Writing",
    bandwidth: "12Gbps",
    jitter: "1.4ms",
  },
  {
    id: "edge-packet-oracle-node",
    from: "packet-oracle",
    to: "skill-node",
    kind: "fiber",
    category: "Backend",
    bandwidth: "38Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-packet-oracle-postgres",
    from: "packet-oracle",
    to: "skill-postgres",
    kind: "fiber",
    category: "Data",
    bandwidth: "36Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-packet-oracle-hono",
    from: "packet-oracle",
    to: "skill-hono",
    kind: "fiber",
    category: "Backend",
    bandwidth: "33Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-lattice-commerce-react",
    from: "lattice-commerce",
    to: "skill-react",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "28Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-lattice-commerce-next",
    from: "lattice-commerce",
    to: "skill-next",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "29Gbps",
    jitter: "0.5ms",
  },
  {
    id: "edge-lattice-commerce-mysql",
    from: "lattice-commerce",
    to: "skill-mysql",
    kind: "fiber",
    category: "Data",
    bandwidth: "25Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-nebula-journal-next",
    from: "nebula-journal",
    to: "skill-next",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "24Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-nebula-journal-tailwind",
    from: "nebula-journal",
    to: "skill-tailwind",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "21Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-nebula-journal-motion",
    from: "nebula-journal",
    to: "skill-motion",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "18Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-relay-mobile-react-native",
    from: "relay-mobile",
    to: "skill-react-native",
    kind: "wireless",
    category: "Mobile",
    bandwidth: "16Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-relay-mobile-android",
    from: "relay-mobile",
    to: "skill-android",
    kind: "wireless",
    category: "Mobile",
    bandwidth: "15Gbps",
    jitter: "1.1ms",
  },
  {
    id: "edge-relay-mobile-zustand",
    from: "relay-mobile",
    to: "skill-zustand",
    kind: "wireless",
    category: "Frontend",
    bandwidth: "14Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-quantum-fleet-node",
    from: "quantum-fleet",
    to: "skill-node",
    kind: "fiber",
    category: "Backend",
    bandwidth: "26Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-quantum-fleet-graphql",
    from: "quantum-fleet",
    to: "skill-graphql",
    kind: "fiber",
    category: "Backend",
    bandwidth: "22Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-quantum-fleet-docker",
    from: "quantum-fleet",
    to: "skill-docker",
    kind: "fiber",
    category: "Backend",
    bandwidth: "20Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-flux-observatory-iot",
    from: "flux-observatory",
    to: "skill-iot",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "13Gbps",
    jitter: "1.3ms",
  },
  {
    id: "edge-flux-observatory-mqtt",
    from: "flux-observatory",
    to: "skill-mqtt",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "12Gbps",
    jitter: "1.4ms",
  },
  {
    id: "edge-flux-observatory-postgres",
    from: "flux-observatory",
    to: "skill-postgres",
    kind: "fiber",
    category: "Data",
    bandwidth: "20Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-mesh-sentinel-networking",
    from: "mesh-sentinel",
    to: "skill-networking",
    kind: "telemetry",
    category: "Networking",
    bandwidth: "24Gbps",
    jitter: "0.9ms",
  },
  {
    id: "edge-mesh-sentinel-websockets",
    from: "mesh-sentinel",
    to: "skill-websockets",
    kind: "telemetry",
    category: "Backend",
    bandwidth: "19Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-orbit-scheduler-hono",
    from: "orbit-scheduler",
    to: "skill-hono",
    kind: "fiber",
    category: "Backend",
    bandwidth: "25Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-orbit-scheduler-typescript",
    from: "orbit-scheduler",
    to: "skill-typescript",
    kind: "fiber",
    category: "Backend",
    bandwidth: "24Gbps",
    jitter: "0.6ms",
  },
  {
    id: "edge-orbit-scheduler-docker",
    from: "orbit-scheduler",
    to: "skill-docker",
    kind: "fiber",
    category: "Backend",
    bandwidth: "22Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-pulse-care-iot",
    from: "pulse-care",
    to: "skill-iot",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "14Gbps",
    jitter: "1.1ms",
  },
  {
    id: "edge-pulse-care-mqtt",
    from: "pulse-care",
    to: "skill-mqtt",
    kind: "telemetry",
    category: "IoT",
    bandwidth: "13Gbps",
    jitter: "1.3ms",
  },
  {
    id: "edge-pulse-care-react-native",
    from: "pulse-care",
    to: "skill-react-native",
    kind: "wireless",
    category: "Mobile",
    bandwidth: "15Gbps",
    jitter: "1.0ms",
  },
  {
    id: "edge-terra-lens-postgres",
    from: "terra-lens",
    to: "skill-postgres",
    kind: "fiber",
    category: "Data",
    bandwidth: "23Gbps",
    jitter: "0.8ms",
  },
  {
    id: "edge-terra-lens-react",
    from: "terra-lens",
    to: "skill-react",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "20Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-terra-lens-three",
    from: "terra-lens",
    to: "skill-three",
    kind: "fiber",
    category: "Frontend",
    bandwidth: "18Gbps",
    jitter: "0.7ms",
  },
  {
    id: "edge-signal-garden-writing",
    from: "signal-garden",
    to: "skill-writing",
    kind: "fiber",
    category: "Writing",
    bandwidth: "12Gbps",
    jitter: "1.2ms",
  },
  {
    id: "edge-signal-garden-open-source",
    from: "signal-garden",
    to: "skill-open-source",
    kind: "fiber",
    category: "Writing",
    bandwidth: "11Gbps",
    jitter: "1.3ms",
  },
];

export const projectDetails: Record<string, ProjectCaseStudy> = {
  "packet-oracle": {
    tagline: "Realtime packet intelligence that pulses with the network.",
    overview:
      "Packet Oracle is a living dashboard that stitches together edge probes, Cloudflare Workers, and Postgres to help SRE teams see packet health before incidents land.",
    highlights: [
      "45+ geo-distributed probes with automatic anomaly escalation",
      "Temporal workflows orchestrating replayable incident drills",
      "GPU-accelerated R3F map with 144Hz rendering budget",
    ],
    architecture: [
      { label: "Ingress", detail: "Cloudflare Workers funnel packets into Hono.js edge routers." },
      { label: "Processing", detail: "Rust workers batch metrics into Kafka, consumed by Node.js services." },
      { label: "Delivery", detail: "Next.js App Router streams React Server Components into the Packet Atlas canvas." },
    ],
    database: {
      engine: "PostgreSQL 16 + TimescaleDB",
      schema: [
        "packets(id, asn, jitter, loss, region, captured_at)",
        "routes(id, source, destination, hops, latency_ms)",
        "alerts(id, severity, opened_at, mitigated_at, owner)",
      ],
      replication: "Logical replication into hot standbys across 3 regions.",
    },
    apis: [
      {
        method: "GET",
        route: "/api/v1/routes/tracer",
        description: "Returns enriched hop data with JIT-projected latencies for the traceroute overlay.",
        runtime: "Hono.js",
      },
      {
        method: "POST",
        route: "/api/v1/incidents",
        description: "Creates incident timelines with Slack + Linear webhooks integrated.",
        runtime: "Express.js",
      },
      {
        method: "WS",
        route: "wss://pulse.packet-oracle.dev/live",
        description: "Streams packet deltas with TTL fades for the HUD throughput meter.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      {
        label: "P95 Latency",
        value: "42ms",
        description: "Across 53k traces per hour during synthetic load tests.",
      },
      {
        label: "Ingestion",
        value: "2.6M pkt/min",
        description: "Sustained with 65% headroom thanks to batched edge writes.",
      },
      {
        label: "MTTR",
        value: "11m",
        description: "Cut from 37m after introducing the predictive anomaly mesh.",
      },
    ],
    timeline: "2024 — Present",
    status: "In Production",
    stack: ["Next.js", "Hono.js", "Node.js", "PostgreSQL", "Kafka", "Timescale"],
  },
  "aether-routing": {
    tagline: "Programmable global routing with human-friendly guardrails.",
    overview:
      "Aether Routing is an SDN control plane offering a policy DSL so platform teams can simulate BGP changes before they propagate.",
    highlights: [
      "Deterministic policy evaluation with TypeScript AST transforms",
      "Realtime diffing of BGP tables streamed into the atlas",
      "Chaos automation harness to rehearse failover",
    ],
    architecture: [
      { label: "Control", detail: "Node.js orchestrator with worker threads per region." },
      { label: "Guard", detail: "Rust-based policy evaluator exposing WebAssembly bindings." },
      { label: "Edge", detail: "Hono.js workers pushing config snapshots via WebSockets." },
    ],
    database: {
      engine: "PostgreSQL + Redis",
      schema: [
        "policies(id, owner, region, version, compiled_ast)",
        "routes(id, prefix, next_hop, status, last_checked)",
      ],
      replication: "Redis streams for ephemeral route events with Postgres persistence.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/v1/policies/compile",
        description: "Compiles DSL statements into WASM guardrails with lint feedback.",
        runtime: "Node.js",
      },
      {
        method: "GET",
        route: "/api/v1/routes/live",
        description: "Streams BGP updates as SSE for the command palette search results.",
        runtime: "Hono.js",
      },
      {
        method: "POST",
        route: "/simulate",
        description: "Spins ephemeral sandboxes to test failover scenarios.",
        runtime: "Express.js",
      },
    ],
    metrics: [
      {
        label: "Propagation",
        value: "7.4s",
        description: "Average config rollout time across 9 PoPs.",
      },
      {
        label: "Policies",
        value: "312",
        description: "Active guardrails authored by platform partners.",
      },
      {
        label: "Uptime",
        value: "99.98%",
        description: "Backed by dual control-plane redundancy.",
      },
    ],
    timeline: "2023 — Present",
    status: "In Production",
    stack: ["Node.js", "Hono.js", "PostgreSQL", "Redis", "Rust"],
  },
  "lattice-commerce": {
    tagline: "Adaptive commerce mesh orchestrating pricing, inventory, and personalization.",
    overview:
      "Lattice Commerce is a composable commerce OS with streaming personalization and resilient payments integrations.",
    highlights: [
      "Realtime availability mesh backed by PostgreSQL logical decoding",
      "A/B experimentation harness with Next.js server actions",
      "Edge-rendered product storytelling with GPU shaders",
    ],
    architecture: [
      { label: "Experience", detail: "Next.js App Router surfaces atomic commerce components." },
      { label: "Pricing", detail: "Node.js services evaluating rules via JSONLogic with caching." },
      { label: "Fulfillment", detail: "Event buses fan out inventory updates into regional stores." },
    ],
    database: {
      engine: "MySQL + PlanetScale",
      schema: [
        "products(id, slug, hero_media, availability, price)",
        "carts(id, user_id, items, currency, updated_at)",
        "orders(id, status, fulfillment_hops, total, tax_breakdown)",
      ],
      replication: "PlanetScale async replicas with CDC to analytics lake.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/checkout",
        description: "Edge checkout funnel verifying stock in <60ms.",
        runtime: "Next.js Route Handler",
      },
      {
        method: "GET",
        route: "/api/pricing",
        description: "Calculates personalized pricebooks with currency fallback.",
        runtime: "Node.js",
      },
      {
        method: "WS",
        route: "wss://mesh.lattice.dev/presence",
        description: "Synchronizes live shoppers for collaborative shopping.",
        runtime: "Express.js",
      },
    ],
    metrics: [
      {
        label: "Conversion",
        value: "+23%",
        description: "Lift from contextual pricing and guided bundling.",
      },
      {
        label: "Edge Latency",
        value: "58ms",
        description: "P95 in multi-region A/B experiments.",
      },
      {
        label: "Orders/Min",
        value: "1.1k",
        description: "Sustained with auto-scaling Node.js workers.",
      },
    ],
    timeline: "2022 — Present",
    status: "In Production",
    stack: ["Next.js", "React", "MySQL", "PlanetScale", "Node.js"],
  },
  "nebula-journal": {
    tagline: "Living knowledge nebula for engineering and product intelligence.",
    overview:
      "Nebula Journal is an MDX knowledge base streaming writing-in-progress and crosslinking design docs in real time.",
    highlights: [
      "RSC-driven content surfaces with GraphQL hydration",
      "Cmd-k enabled semantic search across 1.2k articles",
      "Visual diffing for RFC sign-offs with Motion transitions",
    ],
    architecture: [
      { label: "CMS", detail: "Contentlayer-backed MDX pipeline deployed on Vercel." },
      { label: "Search", detail: "Edge embeddings stored in Postgres pgvector." },
      { label: "Review", detail: "Realtime commentary channels via WebSockets." },
    ],
    database: {
      engine: "PostgreSQL + pgvector",
      schema: [
        "entries(id, title, slug, published_at, embeddings)",
        "revisions(id, entry_id, author, summary, diff)",
        "discussions(id, entry_id, author, message, created_at)",
      ],
      replication: "Read replicas for search queries with connection pooling.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/entries",
        description: "Publishes MDX entries with lint + accessibility checks.",
        runtime: "Next.js Server Actions",
      },
      {
        method: "GET",
        route: "/api/search",
        description: "Vector search returning semantic results ranked by signal strength.",
        runtime: "Hono.js",
      },
      {
        method: "WS",
        route: "wss://nebula.dev/live",
        description: "Enables multi-writer comments with TTL-based presence.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Writers", value: "87", description: "Active contributors in the journal network." },
      { label: "Latency", value: "44ms", description: "Search response time with warmed caches." },
      { label: "Retention", value: "92%", description: "Return rate of weekly knowledge readers." },
    ],
    timeline: "2021 — Present",
    status: "In Production",
    stack: ["Next.js", "PostgreSQL", "pgvector", "GraphQL", "WebSockets"],
  },
  "relay-mobile": {
    tagline: "The offline-first field kit that syncs on its own terms.",
    overview:
      "Relay Mobile equips technicians with offline-first tasking, enabling mesh sync when cellular is unreliable.",
    highlights: [
      "Deterministic conflict resolution with SQLite logical clock",
      "Native modules for BLE provisioning of IoT hardware",
      "Motion-driven guidance to highlight job critical paths",
    ],
    architecture: [
      { label: "App", detail: "React Native + Expo with Zustand stores per feature slice." },
      { label: "Sync", detail: "Hono.js edge sync orchestrator with delta streaming." },
      { label: "Ops", detail: "Android service bridging background tasks and notifications." },
    ],
    database: {
      engine: "SQLite + Drizzle sync",
      schema: [
        "tasks(id, site_id, status, assignee, updated_at)",
        "assets(id, serial, firmware, warranty)",
        "logs(id, task_id, content, synced_at)",
      ],
      replication: "Peer-to-peer delta replication via WebRTC fallback.",
    },
    apis: [
      {
        method: "POST",
        route: "/sync",
        description: "Uploads offline deltas with TTL-based dedupe windows.",
        runtime: "Hono.js",
      },
      {
        method: "GET",
        route: "/tasks",
        description: "Streams prioritized task queues filtered by region.",
        runtime: "Node.js",
      },
      {
        method: "WS",
        route: "wss://relay.dev/mesh",
        description: "Negotiates device-to-device sync when infrastructure is offline.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Sync Success", value: "99.1%", description: "Offline-first merges validated in field pilots." },
      { label: "Battery", value: "-18%", description: "Power savings from background scheduling improvements." },
      { label: "Technicians", value: "540", description: "Active users across 4 countries." },
    ],
    timeline: "2022 — Present",
    status: "In Production",
    stack: ["React Native", "TypeScript", "Hono.js", "SQLite", "WebRTC"],
  },
  "flux-observatory": {
    tagline: "Sensing the planet with resilient, low-power telemetry.",
    overview:
      "Flux Observatory bridges remote sensors, LoRaWAN gateways, and Next.js visualizations to monitor environmental flux.",
    highlights: [
      "Adaptive sampling to extend sensor lifespan by 2.4x",
      "Dynamic topology visualization rendered in R3F",
      "Predictive alerting using pgvector anomaly detection",
    ],
    architecture: [
      { label: "Edge", detail: "ESP32 gateways batching LoRaWAN packets into MQTT." },
      { label: "Ingest", detail: "Node.js consumers persist telemetry into Timescale." },
      { label: "Visualize", detail: "Next.js + Three.js renders living network overlays." },
    ],
    database: {
      engine: "PostgreSQL + Timescale",
      schema: [
        "sensors(id, site, firmware, battery, last_seen)",
        "metrics(sensor_id, reading, unit, observed_at)",
        "anomalies(id, sensor_id, severity, detected_at, cleared_at)",
      ],
      replication: "Continuous archiving to cold storage via WAL-G.",
    },
    apis: [
      {
        method: "MQTT",
        route: "telemetry/+/metrics",
        description: "Sensor-to-gateway uplink with QoS2 deliveries.",
        runtime: "MQTT Broker",
      },
      {
        method: "GET",
        route: "/api/metrics/heatmap",
        description: "Timeseries aggregation for the Flux gradient overlays.",
        runtime: "Hono.js",
      },
      {
        method: "POST",
        route: "/api/anomalies/ack",
        description: "Ack + route anomalies to the command center.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Gateway Uptime", value: "99.3%", description: "Across solar-powered deployments." },
      { label: "Coverage", value: "820 km²", description: "Monitored terrain across coastlines and forests." },
      { label: "Alerts", value: "87/mo", description: "Average actionable anomalies after filtering noise." },
    ],
    timeline: "2021 — Present",
    status: "In Production",
    stack: ["Next.js", "Node.js", "PostgreSQL", "Timescale", "LoRaWAN"],
  },
  "mesh-sentinel": {
    tagline: "Threat hunting that feels like navigating a living nebula.",
    overview:
      "Mesh Sentinel gives NetOps teams a cinematic anomaly explorer with AI-assisted traces and auto-mitigations.",
    highlights: [
      "Streaming anomaly graph with GPU shader trails",
      "Embedded AI copilots summarizing incident heatmaps",
      "TTL fades to spotlight fresh threats in the atlas",
    ],
    architecture: [
      { label: "Collector", detail: "Rust agents push metrics via gRPC." },
      { label: "Core", detail: "Node.js detection service running ML inference." },
      { label: "UI", detail: "Next.js + Three.js powering the living atlas." },
    ],
    database: {
      engine: "PostgreSQL + ClickHouse",
      schema: [
        "events(id, site, signal, score, captured_at)",
        "playbooks(id, title, severity, steps, owner)",
        "edges(from_node, to_node, weight, last_seen)",
      ],
      replication: "Hot/warm storage tiers with TTL policies.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/events",
        description: "Ingests high-volume telemetry with lossless batching.",
        runtime: "Node.js",
      },
      {
        method: "GET",
        route: "/api/anomalies",
        description: "Surface priority anomalies with enriched context.",
        runtime: "Hono.js",
      },
      {
        method: "POST",
        route: "/api/playbooks/execute",
        description: "Automates mitigations via network gear webhooks.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Detect", value: "<4s", description: "Mean detection time for critical events." },
      { label: "Resolve", value: "-63%", description: "Reduction in manual mitigation steps." },
      { label: "Coverage", value: "280k", description: "Devices continuously monitored." },
    ],
    timeline: "2020 — Present",
    status: "In Production",
    stack: ["Next.js", "Node.js", "ClickHouse", "PostgreSQL", "Rust"],
  },
  "orbit-scheduler": {
    tagline: "Event orchestration at the edge of possibility.",
    overview:
      "Orbit Scheduler choreographs fleet operations with an event-driven control plane and real-time visual feedback.",
    highlights: [
      "Edge-first command queue with 11ms roundtrip",
      "Deterministic worker scheduling using Hono.js",
      "Canvas overlays for tracing fleet decisions",
    ],
    architecture: [
      { label: "Dispatch", detail: "Hono.js API orchestrating schedules via Redis streams." },
      { label: "Workers", detail: "Node.js workers executing tasks with exponential backoff." },
      { label: "Insights", detail: "Next.js + Zustand powering operator dashboards." },
    ],
    database: {
      engine: "PostgreSQL + Redis",
      schema: [
        "missions(id, payload, window_start, window_end, status)",
        "vehicles(id, firmware, region, battery, last_seen)",
        "events(id, mission_id, type, payload, created_at)",
      ],
      replication: "Redis replication for ephemeral queues with Postgres persistence.",
    },
    apis: [
      {
        method: "POST",
        route: "/missions",
        description: "Schedules missions with constraint validation.",
        runtime: "Hono.js",
      },
      {
        method: "GET",
        route: "/vehicles/:id",
        description: "Streams telemetry for the traceroute lens.",
        runtime: "Node.js",
      },
      {
        method: "WS",
        route: "wss://orbit.dev/events",
        description: "Notifies clients of mission state changes in realtime.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Dispatch Time", value: "<120ms", description: "Edge command distribution in pilot fleets." },
      { label: "Missions/Day", value: "1.8k", description: "Average orchestrated operations per fleet." },
      { label: "On-time", value: "97.4%", description: "Commitment windows met with dynamic reprioritization." },
    ],
    timeline: "2023 — Present",
    status: "In Production",
    stack: ["Hono.js", "Node.js", "Redis", "PostgreSQL", "Zustand"],
  },
  "pulse-care": {
    tagline: "Empathetic telemetry bridging clinicians and patients.",
    overview:
      "Pulse Care securely links medical IoT devices with real-time dashboards so care teams can act before anomalies escalate.",
    highlights: [
      "HIPAA-compliant data lake with encrypted channels",
      "Adaptive alert routing based on clinician workload",
      "React Native companion with biometric smoothing",
    ],
    architecture: [
      { label: "Device Mesh", detail: "IoT gateways publish vitals through MQTT brokers." },
      { label: "Core", detail: "Node.js services perform anomaly scoring in <90ms." },
      { label: "Clinician", detail: "Next.js dashboards stream prioritized patient queues." },
    ],
    database: {
      engine: "PostgreSQL + Timescale",
      schema: [
        "patients(id, name, risk, clinician_id)",
        "vitals(id, patient_id, metric, value, recorded_at)",
        "alerts(id, patient_id, severity, triggered_at, resolved_at)",
      ],
      replication: "Timescale continuous aggregates with encrypted archival.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/v1/vitals",
        description: "Securely ingests device vitals with signature validation.",
        runtime: "Hono.js",
      },
      {
        method: "GET",
        route: "/api/v1/patients/:id",
        description: "Streams patient dashboards with SSE to mobile clients.",
        runtime: "Node.js",
      },
      {
        method: "WS",
        route: "wss://pulse-care.dev/alerts",
        description: "Pushes clinician-specific alert queues with TTL decay.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Response", value: "-41%", description: "Time to clinician acknowledgment dropped post-launch." },
      { label: "Coverage", value: "12 clinics", description: "Pilots across cardiology and oncology wards." },
      { label: "Devices", value: "3.8k", description: "Encrypted medical IoT devices reporting continuously." },
    ],
    timeline: "2023 — Present",
    status: "In Production",
    stack: ["Next.js", "Node.js", "PostgreSQL", "Timescale", "MQTT", "React Native"],
  },
  "quantum-fleet": {
    tagline: "Predictive fleet intelligence with adaptive routing.",
    overview:
      "Quantum Fleet unifies telematics, predictive maintenance, and driver UX with a unified event mesh.",
    highlights: [
      "Predictive routing with per-vehicle ETA variance modeling",
      "Command palette for dispatchers with global keyboarding",
      "Edge workers pushing over-the-air updates within 60 seconds",
    ],
    architecture: [
      { label: "Gateway", detail: "CAN bus adapters publish metrics via MQTT to edge nodes." },
      { label: "Brain", detail: "Node.js + GraphQL orchestrate route optimization services." },
      {
        label: "Experience",
        detail: "Next.js + Mapbox deliver dispatcher cockpit + driver app.",
      },
    ],
    database: {
      engine: "PostgreSQL + Redis",
      schema: [
        "vehicles(id, vin, health_score, firmware, last_seen)",
        "journeys(id, vehicle_id, origin, destination, eta, status)",
        "telemetry(id, vehicle_id, metric, value, captured_at)",
      ],
      replication: "Redis pub/sub for hot signals, Postgres for historical insight.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/v1/journeys",
        description: "Creates optimized journeys factoring live traffic + load.",
        runtime: "Node.js",
      },
      {
        method: "GET",
        route: "/graphql",
        description: "Gateway for dashboards and mobile clients using persisted queries.",
        runtime: "GraphQL Yoga",
      },
      {
        method: "WS",
        route: "wss://quantum-fleet.dev/telemetry",
        description: "High-frequency vehicle telemetry with TTL-based downsampling.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "On-time", value: "+18%", description: "Improvement in arrival predictions across fleets." },
      { label: "Fuel", value: "-9%", description: "Savings from adaptive routing + driver nudges." },
      { label: "Vehicles", value: "4.6k", description: "Vehicles actively monitored each day." },
    ],
    timeline: "2022 — Present",
    status: "In Production",
    stack: ["Next.js", "Node.js", "GraphQL", "Redis", "PostgreSQL"],
  },
  "terra-lens": {
    tagline: "Geospatial impact dashboard with sensor overlays.",
    overview:
      "Terra Lens unifies satellite, drone, and IoT feeds to surface environmental change for sustainability teams.",
    highlights: [
      "Shader-based geospatial overlays with dynamic packet trails",
      "PostGIS analytics with typed server actions",
      "Interoperable APIs for scientists and policy makers",
    ],
    architecture: [
      { label: "Ingest", detail: "Next.js server actions orchestrate file uploads into S3." },
      { label: "Analytics", detail: "PostGIS functions compute delta metrics for each grid cell." },
      { label: "Experience", detail: "Three.js + Deck.gl blend heightmaps with live packets." },
    ],
    database: {
      engine: "PostgreSQL + PostGIS",
      schema: [
        "layers(id, slug, type, last_refresh, author)",
        "measurements(id, layer_id, geometry, metric, captured_at)",
        "reports(id, layer_id, headline, summary, published_at)",
      ],
      replication: "Logical replication into analytics warehouse for researchers.",
    },
    apis: [
      {
        method: "POST",
        route: "/api/layers",
        description: "Publishes new geospatial layers with validation + preview renders.",
        runtime: "Next.js Route Handler",
      },
      {
        method: "GET",
        route: "/api/measurements",
        description: "Streams aggregated metrics for map overlays.",
        runtime: "Hono.js",
      },
      {
        method: "GET",
        route: "/api/reports",
        description: "Serves long-form analysis with incremental static regeneration.",
        runtime: "Next.js",
      },
    ],
    metrics: [
      { label: "Refresh", value: "15m", description: "Fresh satellite composites for rapid response teams." },
      { label: "Stakeholders", value: "28", description: "Organizations using Terra Lens for decision making." },
      { label: "Regions", value: "63", description: "Regions continuously monitored for change." },
    ],
    timeline: "2021 — Present",
    status: "In Production",
    stack: ["Next.js", "PostgreSQL", "PostGIS", "Three.js", "Deck.gl"],
  },
  "signal-garden": {
    tagline: "Distributed UX essays cultivated like circuits.",
    overview:
      "Signal Garden is where essays, talks, and open source ideas bloom with interactive demos.",
    highlights: [
      "Immersive MDX narratives with animated packet routes",
      "Talk-ready slides auto-generated from writing outlines",
      "Community patches accepted via open governance board",
    ],
    architecture: [
      { label: "Writing", detail: "MDX + Contentlayer pipeline with design token hydration." },
      { label: "Stage", detail: "Next.js static export for talk-ready decks." },
      { label: "Community", detail: "GitHub Actions triaging contributions with tests." },
    ],
    database: {
      engine: "PostgreSQL",
      schema: [
        "essays(id, slug, title, published_at, topic)",
        "endorsements(id, essay_id, skill, issued_at)",
        "events(id, talk, venue, date, media_link)",
      ],
      replication: "Supabase replica powering public API explorers.",
    },
    apis: [
      {
        method: "GET",
        route: "/api/essays",
        description: "Returns essays filtered by topic + signal strength.",
        runtime: "Next.js",
      },
      {
        method: "GET",
        route: "/api/events",
        description: "Feeds talk calendars into community dashboards.",
        runtime: "Next.js",
      },
      {
        method: "POST",
        route: "/api/endorsements",
        description: "Allows readers to send BGP-like endorsements.",
        runtime: "Node.js",
      },
    ],
    metrics: [
      { label: "Readers", value: "14k/mo", description: "Unique readers exploring distributed UX content." },
      { label: "Talks", value: "38", description: "Talks delivered across meetups and conferences." },
      { label: "Repos", value: "12", description: "Open source projects maintained through Signal Garden." },
    ],
    timeline: "2019 — Present",
    status: "Open Source",
    stack: ["Next.js", "Contentlayer", "Tailwind CSS", "Node.js"],
  },
};
